### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yzh990918** [EchoDzg/SpBook#1]
npm run dev 报一堆的错误

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by EchoDzg** [comment]
刚我试了下，下载最新的node 编译的时候有点问题。 报错提示是  node-sass无法下载。 可以 将 package.json 里的  node-sass  版本改为  ^4.9.4  。 重新编译安装即可。
